// Barrel file for all slides
export '01_title_slide.dart';
export '02_self_intro_slide.dart';
export '03_ai_driven_dev_slide.dart';
export '04_next_stage_slide.dart';
export '05_feedback_loop_definition_slide.dart';
export '06_demo_slide.dart';
export '07_main_topic_slide.dart';
export '08_ui_verification_architecture_slide.dart';
export '09_mcp_tools_overview_slide.dart';
export '10_dart_mcp_complement_slide.dart';
export '11_approach_comparison_slide.dart';
export '12_ios_internals_slide.dart';
export '13_android_approaches_slide.dart';
export '14_marionette_vm_service_slide.dart';
export '15_app_side_requirements_slide.dart';
export '16_implementation_example_slide.dart';
export '17_comparison_table_slide.dart';
export '18_summary_slide.dart';
